---
- hosts: all

  tasks:
   - name: "push hosts"
     copy: src=os_conf/hosts dest=/root/hosts force=yes
   - name: "overwrite hosts"
     command: cp /root/hosts /etc/hosts
   - name: "push bash_profile"
     copy: src=os_conf/.bash_profile dest=/root/.bash_profile force=yes
